import Link from "next/link";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Image from "next/image";
import Navbar from "@/components/common/Navbar";

export const metadata: Metadata = {
  title: "UwUmedia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} antialiased`}
      >
        <header className="border-b-2 border-b-corporative">
          <div className="max-w-screen-2xl m-auto flex flex-wrap justify-between">
            <Link href="/">
              <Image src='/logos/logo-primary.svg' alt="Logo UwUmedia" width={250} height={300} priority unoptimized={true}/>
            </Link>
            <Navbar />
          </div>
        </header>
        <main className="max-w-screen-2xl m-auto px-4 2xl:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
